config/routes.rb
Rails.application.routes.draw do
  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'auth/discourse', controller: :auth, action: :discourse
  get 'auth_comeback/discourse', controller: :auth_comeback, action: :discourse

  root to: 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  include AASM

  belongs_to :user

  aasm column: 'state' do
    state :new, initial: true
    state :approved
    state :rejected

    event :approve do
      transitions from: :new, to: :approved
    end

    event :reject do
      transitions from: [:new, :approved], to: :rejected
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user_session, :current_user

  private

  def authenticate_user!
    redirect_to root_path, notice: 'You need to be signed in!' unless current_user
  end

  def current_user_session
    return @current_user_session if defined?(@current_user_session)

    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)

    @current_user = current_user_session&.user
  end
end

app/controllers/auth_comeback_controller.rb
class AuthComebackController < ApplicationController
  def discourse
    sso = SsoWithDiscourse::Sso.new
    sso.nonce = session[:sso]['nonce']
    sso.parse(params)

    if sso.status == 'success'
      email = sso.user_info[:email]
      user = User.find_by(email: email)

      attrs = {
        email: email
      }

      if user.blank?
        user = User.create!(attrs.merge!(
          active: true,
          approved: true,
          confirmed: true
        ))
      end

      # Create session
      UserSession.new(user).save!

      redirect_to root_path, notice: 'Zalogowano pomyślnie!'
    else
      redirect_to root_path, notice: 'Coś poszło nie tak przy próbie zalogowania. Spróbuj ponownie za chwilę.'
    end
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def discourse
    sso = SsoWithDiscourse::Sso.new
    sso.return_url = auth_comeback_discourse_url
    session[:sso] = sso

    redirect_to sso.request_url
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    @events = Event.order(beginning_at: :asc).group_by { |e| e.beginning_at.beginning_of_month }
  end

  def new
    @event = EventForm.new
  end

  def create
    @event = EventForm.new(event_form_params)
    @event.user = current_user

    if @event.valid?
      if @event.existing_event.present?
        redirect_to @event.existing_event, notice: 'Event already added.'
      else
        @event.save!
        redirect_to events_path, notice: 'Event was successfully created.'
      end
    else
      render :new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_form_params
    params.require(:event_form).permit(:title, :beginning_at, :city, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, url: events_path) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :beginning_at %>
    <%= form.date_field :beginning_at %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :url, 'Link' %>
    <%= form.url_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.slim
.nav.flex.items-center.justify-between.flex-wrap.bg-gray-200.p-6
  .flex-shrink-0.flex.items-center
    span.font-semibold.text-xl.tracking-tight events.hcxp

  .w-full.flex-grow
    div.flex-grow
      a.inline-block + Add event
      a.inline-block Twitter
      a.inline-block RSS

.flex.flex-wrap
  .ml-auto.mr-auto(class="w-1/2")

    div.bg-gray-100.p-10.mb-6.mt-4.text-center.border.border-gray-300
      h1.text-3xl.font-semibold.text-gray-800.mb-2 Hardcore-punk events directory
      p.text-lg.text-gray-700 Made a library? Written a blog post? Found a useful tutorial? Share it with the Ruby community here or just enjoy what everyone else has found!

    form.flex.mb-6
      input.border.border-gray-200.p-4(class="w-2/3" name="q" value=params[:q])
      input.bg-gray-200.p-4.font-bold(type="submit" value="Search" class="w-1/3")

    - @events.each do |month, events|
      .bg-gray-200.p-2.font-bold.text-gray-500.mb-3
        h2 = month.strftime('%B %Y')

      - events.each do |event|
        article.mb-6.px-2
          .flex
            div(class="w-2/3")
              p.text-xs.uppercase.text-gray-600
                = link_to event.city, events_path(q: event.city)
                |, PL

              = link_to event.title, event, class: 'text-lg'

            .text-right(class="w-1/3")
              p.text-sm.text-gray-600
                = distance_of_time_in_words(Time.current, event.beginning_at)

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Mentions:</strong>
  <%= @event.mentions %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @event.authors %>
</p>

<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @event.country %>
</p>

<p>
  <strong>Beginning at:</strong>
  <%= @event.beginning_at %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @event.facebook_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @event.state %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HcxpEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'stylesheets', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>